name: Node-CI

on:
  push:
    branches: [ master, stage, develop ]

jobs:
  build-prod:
    if: github.ref == 'refs/heads/master'
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install npm dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo PRODUCTION=${{ secrets.PRODUCTION }} >> .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo WQ_PROVIDER=${{ secrets.WQ_PROVIDER }} >> .env
          echo WQ_ORACLE_URL=${{ secrets.WQ_ORACLE_URL }} >> .env

      - name: Run generate static task
        run: npm run generate

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

  build-develop:
    if: github.ref == 'refs/heads/develop'
    environment: develop
    runs-on: ubuntu-latest

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install npm dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo PRODUCTION=${{ secrets.PRODUCTION }} >> .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo WQ_PROVIDER=${{ secrets.WQ_PROVIDER }} >> .env
          echo WQ_ORACLE_URL=${{ secrets.WQ_ORACLE_URL }} >> .env

      - name: Run generate static task
        run: npm run generate

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

  build-stage:
    if: github.ref == 'refs/heads/stage'
    environment: stage
    runs-on: ubuntu-latest

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install npm dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo PRODUCTION=${{ secrets.PRODUCTION }} >> .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo WQ_PROVIDER=${{ secrets.WQ_PROVIDER }} >> .env
          echo WQ_ORACLE_URL=${{ secrets.WQ_ORACLE_URL }} >> .env

      - name: Run generate static task
        run: npm run generate

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
